import { useMemo, useState } from 'react'
import type { ContractStatus, MaintenanceContract } from '../types/contract'
import { derivedStatus, ddayText, formatDate, formatWon, statusLabel } from '../utils/contracts'
import StatusBadge from '../components/StatusBadge'

interface Props { contracts: MaintenanceContract[]; onOpen: (id: string) => void; onEdit: (id: string) => void; onDelete: (id: string) => void; onRegister: () => void }

export default function ContractListPage({ contracts, onOpen, onEdit, onDelete, onRegister }: Props) {
  const [query, setQuery] = useState('')
  const [filter, setFilter] = useState<'all' | ContractStatus>('all')
  const filtered = useMemo(() => contracts.filter((item) => (item.companyName + item.managerName + item.businessNumber).toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || derivedStatus(item) === filter)), [contracts, query, filter])
  const remove = (contract: MaintenanceContract) => { if (window.confirm(`“${contract.companyName}” 계약 정보를 삭제할까요?`)) onDelete(contract.id) }
  return <div className="mx-auto max-w-6xl space-y-5"><section className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-indigo-600">CONTRACTS</p><h1 className="mt-1 text-2xl font-bold text-slate-900">유지보수 업체 목록</h1><p className="mt-2 text-sm text-slate-500">총 {contracts.length}개 업체의 계약 정보를 관리합니다.</p></div><button className="btn-primary" onClick={onRegister}>＋ 계약서 등록</button></section>
    <section className="panel p-4"><div className="flex flex-col gap-3 sm:flex-row"><input className="input flex-1" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="업체명, 담당자, 사업자번호 검색" /><select className="input sm:w-40" value={filter} onChange={(e) => setFilter(e.target.value as 'all' | ContractStatus)}><option value="all">전체 상태</option>{Object.entries(statusLabel).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div></section>
    <section className="panel overflow-hidden"><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[780px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-5 py-4 font-semibold">업체명</th><th className="px-4 py-4 font-semibold">담당자</th><th className="px-4 py-4 font-semibold">연락처</th><th className="px-4 py-4 font-semibold">계약기간</th><th className="px-4 py-4 font-semibold">월 유지보수 금액</th><th className="px-4 py-4 font-semibold">상태</th><th className="px-5 py-4 text-right font-semibold">관리</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((item) => { const status = derivedStatus(item); return <tr key={item.id} className="hover:bg-slate-50"><td className="px-5 py-4"><button onClick={() => onOpen(item.id)} className="font-semibold text-slate-800 hover:text-indigo-600">{item.companyName}</button><p className="mt-1 text-xs text-slate-400">{item.businessNumber || '사업자번호 미입력'}</p></td><td className="px-4 py-4">{item.managerName || '-'}</td><td className="px-4 py-4 text-slate-600">{item.managerPhone || '-'}</td><td className="px-4 py-4 text-slate-600"><p>{formatDate(item.contractStartDate)} ~</p><p>{formatDate(item.contractEndDate)} <span className="ml-1 font-semibold text-amber-600">{ddayText(item.contractEndDate)}</span></p></td><td className="px-4 py-4 font-medium">{formatWon(item.monthlyFee)}</td><td className="px-4 py-4"><StatusBadge status={status} /></td><td className="px-5 py-4"><div className="flex justify-end gap-1"><button className="btn-secondary min-h-9 px-2.5 text-xs" onClick={() => onOpen(item.id)}>상세</button><button className="btn-secondary min-h-9 px-2.5 text-xs" onClick={() => onEdit(item.id)}>수정</button><button className="btn-danger min-h-9 px-2.5 text-xs" onClick={() => remove(item)}>삭제</button></div></td></tr> })}</tbody></table></div>
      <div className="divide-y divide-slate-100 md:hidden">{filtered.map((item) => { const status = derivedStatus(item); return <article key={item.id} className="p-4"><div className="flex items-start justify-between gap-3"><button onClick={() => onOpen(item.id)} className="text-left font-bold text-slate-900">{item.companyName}<span className="mt-1 block text-xs font-normal text-slate-500">{item.managerName || '담당자 미입력'} · {item.managerPhone || '-'}</span></button><StatusBadge status={status} /></div><div className="mt-3 grid grid-cols-2 gap-2 rounded-lg bg-slate-50 p-3 text-xs text-slate-600"><span>계약 종료</span><strong className="text-right text-amber-700">{formatDate(item.contractEndDate)} ({ddayText(item.contractEndDate)})</strong><span>월 유지보수</span><strong className="text-right text-slate-800">{formatWon(item.monthlyFee)}</strong></div><div className="mt-3 flex gap-2"><button className="btn-secondary min-h-10 flex-1 text-xs" onClick={() => onOpen(item.id)}>상세</button><button className="btn-secondary min-h-10 flex-1 text-xs" onClick={() => onEdit(item.id)}>수정</button><button className="btn-danger min-h-10 px-3 text-xs" onClick={() => remove(item)}>삭제</button></div></article>})}</div>
      {filtered.length === 0 && <p className="px-5 py-16 text-center text-sm text-slate-500">조건에 맞는 업체가 없습니다.</p>}
    </section>
  </div>
}
