import type { MaintenanceContract } from '../types/contract'
import { ddayText, derivedStatus, formatDate, formatWon, statusLabel } from '../utils/contracts'
import StatusBadge from '../components/StatusBadge'

interface Props { contract: MaintenanceContract; onEdit: () => void; onDelete: () => void; onBack: () => void }

export default function ContractDetailPage({ contract, onEdit, onDelete, onBack }: Props) {
  const status = derivedStatus(contract)
  const log = `${contract.companyName || '업체'} 유지보수 계약정보 등록 완료 / 계약기간 ${contract.contractStartDate || '-'} ~ ${contract.contractEndDate || '-'}`
  const fields = [['사업자등록번호', contract.businessNumber], ['대표자명', contract.ceoName], ['담당자', contract.managerName], ['담당자 연락처', contract.managerPhone], ['이메일', contract.email], ['주소', contract.address], ['계약 시작일', formatDate(contract.contractStartDate)], ['계약 종료일', formatDate(contract.contractEndDate)], ['월 유지보수 금액', formatWon(contract.monthlyFee)], ['계약 상태', statusLabel[status]]]
  return <div className="mx-auto max-w-4xl space-y-5"><button onClick={onBack} className="text-sm font-semibold text-slate-500 hover:text-indigo-600">← 업체 목록으로</button><section className="panel overflow-hidden"><div className="border-b border-slate-100 bg-gradient-to-r from-indigo-50 to-white px-5 py-6 sm:px-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="flex items-center gap-2"><h1 className="text-2xl font-bold text-slate-900">{contract.companyName}</h1><StatusBadge status={status} /></div><p className="mt-2 text-sm text-slate-500">등록일 {new Date(contract.createdAt).toLocaleDateString('ko-KR')}</p></div><div className="rounded-xl bg-white px-4 py-3 text-right shadow-sm ring-1 ring-slate-100"><p className="text-xs font-medium text-slate-500">계약 만료</p><p className="mt-1 text-xl font-bold text-amber-600">{ddayText(contract.contractEndDate)}</p></div></div></div>
    <div className="grid gap-x-8 gap-y-0 p-5 sm:grid-cols-2 sm:p-7">{fields.map(([label, value]) => <div key={label} className="border-b border-slate-100 py-3"><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-1 break-words text-sm font-semibold text-slate-800">{value || '-'}</p></div>)}<div className="border-b border-slate-100 py-3 sm:col-span-2"><p className="text-xs font-medium text-slate-500">지원 범위</p><p className="mt-1 whitespace-pre-wrap text-sm text-slate-800">{contract.supportScope || '-'}</p></div><div className="border-b border-slate-100 py-3 sm:col-span-2"><p className="text-xs font-medium text-slate-500">비고</p><p className="mt-1 whitespace-pre-wrap text-sm text-slate-800">{contract.memo || '-'}</p></div><div className="py-3 sm:col-span-2"><p className="text-xs font-medium text-slate-500">계약서 파일명</p><p className="mt-1 text-sm font-semibold text-indigo-700">▣ {contract.pdfFileName || '등록된 파일 없음'}</p></div></div>
    <div className="flex flex-col-reverse gap-2 border-t border-slate-100 px-5 py-4 sm:flex-row sm:justify-end sm:px-7"><button onClick={onDelete} className="btn-danger">삭제</button><button onClick={onEdit} className="btn-primary">수정</button></div></section>
    <section className="panel p-5"><h2 className="font-bold text-slate-900">업무일지 문구</h2><p className="mt-1 text-sm text-slate-500">업무일지에 바로 붙여 넣을 수 있는 문구입니다.</p><div className="mt-4 rounded-lg bg-slate-50 p-4 text-sm leading-6 text-slate-700">{log}</div><button className="btn-secondary mt-3" onClick={() => navigator.clipboard?.writeText(log)}>문구 복사</button></section>
  </div>
}
